version: 2

models:
  - name: dim_customers
    description: One record per customer
    columns:
      - name: customer_id
        description: Primary key
        tests:
          - unique
          - not_null
      - name: first_order_date
        description: NULL when a customer has not yet placed an order

  - name: fct_orders
    description: One record per order
    columns:
      - name: order_id
        description: Primary key
        tests:
          - unique
          - not_null
      - name: customer_id
        description: Foreign key to the dim_customers.customer_id
        tests:
          - relationships:
              to: ref('dim_customers')
              field: customer_id
      - name: order_date
        description: the date when the order are placed
      - name: amount
        description: the total payment amount for an order

          